version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linkpulse"
s3_bucket = ""
s3_prefix = "linkpulse"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
image_repositories = []